required_options = ['id', 'type', 'cost', 'emoji']

images_folder = 'bin/images/'

lenses_description = {
    'en': 'Lenses that change pupils color',
    'ru': 'Линзы, меняющие цвет зрачков'
}
eye_emotion_description = {
    'en': 'Change the mood of your pig',
    'ru': 'Поменяйте настроение своему хряку'
}
eyes_description = {
    'en': 'Big lenses that change eye color',
    'ru': 'Большие линзы, меняющие цвет глаз'
}
tattoo_description = {
    'en': 'Tattoo for your pig',
    'ru': 'Татуировка для хряка'
}
piercing_description = {
    'en': 'Pig piercing',
    'ru': 'Пирсинг для хряка'
}
default_lenses_price = 80
default_tattoo_price = 30

items = {
    'poop': {'name': {'en': 'Poops',
                      'ru': 'Навоз'},
             'desc': {
                 'en': 'Pure, and most importantly, natural manure',
                 'ru': 'Чистый, а самое главное натуральный навоз'
             },
             'components': ['use', 'sell'],
             'type': 'resource',
             'cost': 1,
             'rarity': '1',
             'emoji': '💩',
             'image_file': f'{images_folder}poop.png'},
    'coins': {'name': {'en': 'Coins',
                       'ru': 'Монеты'},
              'desc': {
                  'en': 'Coins for which you can buy something',
                  'ru': 'Монеты, за которые можно что-то купить'
              },
              'type': 'money',
              'emoji': '🪙'},
    'weight': {'name': {'en': 'Weight',
                        'ru': 'Вес'},
               'desc': {
                   'en': 'Pig weight in kilograms',
                   'ru': 'Вес хряка в килограммах'
               },
               'type': 'weight',
               'emoji': '🐷'},
    'lard': {'name': {'en': 'Lard',
                      'ru': 'Сало'},
             'desc': {
                 'en': 'The freshest and most natural lard you can find',
                 'ru': 'Самое свежее и натуральное сало, которое можно найти'
             },
             'type': 'resource',
             'cost': 15,
             'rarity': '1',
             'emoji': '🥓',
             'cooked': 'barbecue',
             'image_file': f'{images_folder}lard.png'},
    'barbecue': {'name': {'en': 'Barbecue',
                          'ru': 'Шашлык'},
                 'desc': {
                     'en': 'Delicious homemade barbecue',
                     'ru': 'Очень вкусный шашлык, приготовленный в домашних условиях'
                 },
                 'type': 'resource',
                 'cost': 25,
                 'rarity': '2',
                 'emoji': '🍖',
                 'image_file': f'{images_folder}barbecue.png'},
    'beer': {'name': {'en': 'Beer',
                          'ru': 'Пиво'},
                 'desc': {
                     'en': 'True beer, crafted with love',
                     'ru': 'Настоящее пиво, созданное с любовью'
                 },
                 'type': 'resource',
                 # 'cost': 25,
                 'rarity': '2',
                 'emoji': '🍺',
                 'image_file': f'{images_folder}beer.png'},
    'laxative': {'name': {'en': 'Laxative',
                          'ru': 'Слабительное'},
                 'desc': {
                     'en': 'When used, a pig will give 50 % more manure, '
                           'but at the same time the pig will gain weight by 30% less',
                     'ru': 'При использовании свинья даст на 50 % больше навоза, '
                           'но при этом хряк будет набирать на 30% меньше веса'
                 },
                 'type': 'consumable',
                 'pooping_boost': 1.5,
                 'weight_boost': .7,
                 # 'cost': 5,
                 'shop_price': 10,
                 'cooldown': {5: 45 * 3600},
                 'method_of_obtaining': 'shop:always',
                 'rarity': '2',
                 'emoji': '💊',
                 'image_file': f'{images_folder}laxative.png',
                 },
    'knife': {'name': {'en': 'Knife',
                       'ru': 'Нож'},
              'desc': {
                  'en': 'With this knife, you can carefully take fat from a pig',
                  'ru': 'С этим ножом вы можете аккуратно снимать сало со свиньи'
              },
              'components': ['sell'],
              'type': 'tool',
              # 'cost': 100,
              'shop_price': 250,
              'method_of_obtaining': 'shop:always',
              'rarity': '3',
              'emoji': '🔪',
              'image_file': f'{images_folder}knife.png',
              },
    'grill': {'name': {'en': 'Grill',
                       'ru': 'Мангал'},
              'desc': {
                  'en': 'On this grill you can fry something',
                  'ru': 'На этом мангале вы можете пожарить что-то'
              },
              'components': ['sell'],
              'type': 'tool',
              # 'cost': 200,
              'shop_price': 500,
              'method_of_obtaining': 'shop:always',
              'rarity': '3',
              'emoji': '🔥',
              'image_file': f'{images_folder}mangal.png',
              },

    # cases

    'common_case': {'name': {'en': 'Common case',
                             'ru': 'Обычный кейс'},
                    'desc': {
                        'en': 'Regular case that can be opened',
                        'ru': 'Обычный кейс, который можно открыть'
                    },
                    'components': ['use'],
                    'type': 'case',
                    # 'cost': 50,
                    'shop_price': 120,
                    'cooldown': {2: 22 * 3600},
                    'method_of_obtaining': 'shop:cases',
                    'rarity': '3',
                    'emoji': '🎁',
                    'image_file': f'{images_folder}common_case.png',
                    },
    'rare_case': {'name': {'en': 'Rare case',
                           'ru': 'Редкий кейс'},
                  'desc': {
                      'en': 'Rare case that can be opened',
                      'ru': 'Редкий кейс, который можно открыть'
                  },
                  'components': ['use'],
                  'type': 'case',
                  # 'cost': 100,
                  'cooldown': {1: 22 * 3600},
                  'shop_price': 210,
                  'method_of_obtaining': 'shop:cases',
                  'rarity': '4',
                  'emoji': '🎁',
                  'image_file': f'{images_folder}common_case.png',
                  },
    'epic_case': {'name': {'en': 'Epic case',
                           'ru': 'Эпический кейс'},
                  'desc': {
                      'en': 'Epic case that can be opened',
                      'ru': 'Эпический кейс, который можно открыть'
                  },
                  'components': [],
                  'type': 'case',
                  'cost': 200,
                  'shop_price': 400,
                  # 'method_of_obtaining': 'shop:cases',
                  'rarity': '5',
                  'emoji': '🎁',
                  'image_file': f'{images_folder}common_case.png',
                  },
    # 'hat_case': {'name': {'en': 'Hat case',
    #                          'ru': 'Шляпочный кейс'},
    #                 'desc': {
    #                     'en': 'Regular case that can be opened',
    #                     'ru': 'Обычный кейс, который можно открыть'
    #                 },
    #                 'components': ['use'],
    #                 'type': 'case',
    #                 'cost': 50,
    #                 'shop_price': 120,
    #                 'cooldown': {2: 22 * 3600},
    #                 'method_of_obtaining': 'shop:cases',
    #                 'rarity': '3',
    #                 'emoji': '🎁',
    #                 'image_file': f'{images_folder}common_case.png',
    #                 },

    # pets
    'pet_hryak_default': {'name': {'en': 'Mini Hryak',
                                   'ru': 'Мини Хряк'},
                          'desc': {
                              'en': "It's a mini pig! It will give you 5% more manure!",
                              'ru': 'Это же мини Хряк! Он будет давать вам на 5% больше навоза!'
                          },
                          'components': ['hide'],
                          'type': 'pet',
                          'pooping_boost': 1.05,
                          'rarity': '3',
                          'emoji': '🐷',
                          'pregnancy_duration': 36 * 3600
                          },

    # hats
    'cylinder': {'name': {'en': 'Cylinder',
                          'ru': 'Цилиндр'},
                 'desc': {
                     'en': 'Very fashionable top hat',
                     'ru': 'Очень модный цилиндр'
                 },
                 'type': 'skin:hat',
                 'shop_price': 140,
                 'method_of_obtaining': 'shop:daily',
                 'rarity': '3',
                 'emoji': '🎩'
                 },
    'manga_hat': {'name': {'en': 'Cylinder',
                          'ru': 'Цилиндр'},
                 'desc': {
                     'en': 'Black and white hat straight from the manga',
                     'ru': 'Черно-белая шляпа, прямиком из манги'
                 },
                 'type': 'skin:hat',
                 'shop_price': 80,
                 'method_of_obtaining': 'shop:daily',
                 'rarity': '3',
                 'emoji': '🎩'
                 },
    'low_budget_cylinder': {'name': {'en': 'Low budget cylinder',
                          'ru': 'Низко бюджетный цилиндр'},
                 'desc': {
                     'en': 'The creator of the Hryak did not have enough budget to make a normal skin',
                     'ru': 'Создателю Хряка не хватило бюджета, чтобы сделать нормальный скин'
                 },
                 'type': 'skin:hat',
                 'shop_price': 1000,
                 'method_of_obtaining': 'shop:daily',
                 'rarity': '6',
                 'emoji': '🎩'
                 },
    'green_cylinder': {'name': {'en': 'Green cylinder',
                          'ru': 'Цилиндр Находкинса'},
                 'desc': {
                     'en': 'How bad could I be?',
                     'ru': 'Ну ра-а-азве я плохой?'
                 },
                 'type': 'skin:hat',
                 'shop_price': 140,
                 'method_of_obtaining': 'shop:daily',
                 'rarity': '3',
                 'emoji': '🎩'
                 },
    'luffy_hat': {'name': {'en': 'Luffy hat',
                           'ru': 'Шляпа луффи'},
                  'desc': {
                      'en': 'Gomu gomu no',
                      'ru': 'Gomu gomu no'
                  },
                  'type': 'skin:hat',
                  'shop_price': 120,
                  'method_of_obtaining': 'shop:daily',
                  'rarity': '3',
                  'emoji': '👒'
                  },
    'box_hat': {'name': {'en': 'Box hat',
                           'ru': 'Коробка'},
                  'desc': {
                      'en': "This box looks good, doesn't it?",
                      'ru': 'А эта коробка выглядит неплохо, да?'
                  },
                  'type': 'skin:hat',
                  'shop_price': 80,
                  'method_of_obtaining': 'shop:daily',
                  'rarity': '3',
                  'emoji': '📦'
                  },
    'aquarium_hat': {'name': {'en': 'Aquarium',
                         'ru': 'Аквариум'},
                'desc': {
                    'en': "Who wants to wear an aquarium on their head",
                    'ru': 'Кто захочет носить аквариум на голове'
                },
                'type': 'skin:hat',
                'shop_price': 150,
                'method_of_obtaining': 'shop:daily',
                'rarity': '4',
                'emoji': '🐟'
                },
    'unicorn_hat': {'name': {'en': 'Unicorn horn',
                         'ru': 'Рог'},
                'desc': {
                    'en': "Conjure something with this horn",
                    'ru': 'Наколдуй этим рогом что нибудь'
                },
                'type': 'skin:hat',
                'shop_price': 100,
                'method_of_obtaining': 'shop:daily',
                'rarity': '3',
                'emoji': '🌈'
                },
    'nitro_hat': {'name': {'en': 'Nitro',
                             'ru': 'Нитро'},
                    'desc': {
                        'en': "Only for true legends",
                        'ru': 'Только для настоящих легенд'
                    },
                    'type': 'skin:hat',
                    # 'shop_price': 100,
                    'rarity': '6',
                    'emoji': '💎'
                    },
    'speedwagon_hat': {'name': {'en': 'Speedwagon hat',
                                'ru': 'Шляпа спидвагона'},
                       'desc': {
                           'en': 'Idk, didn\'t watch',
                           'ru': 'Почувствуй себя спидвагоном'
                       },
                       'type': 'skin:hat',
                       'shop_price': 120,
                       'method_of_obtaining': 'shop:daily',
                       'rarity': '3',
                       'emoji': '👒'
                       },
    'diamond_helmet': {'name': {'en': 'Diamond helmet',
                                'ru': 'Алмазный шлем'},
                       'desc': {
                           'en': "I think I've already seen this helmet in some game",
                           'ru': 'Кажется я уже видел этот шлем в какой то игре'
                       },
                       'type': 'skin:hat',
                       'shop_price': 120,
                       'method_of_obtaining': 'shop:daily',
                       'rarity': '3',
                       'emoji': '🪖'
                       },
    'kid_cap': {'name': {'en': 'Kid cap',
                                'ru': 'Детская кепка'},
                       'desc': {
                           'en': "If children were the flowers of life, then they would be weeds.",
                           'ru': 'Если бы дети были цветами жизни, то они были бы сорняками'
                       },
                       'type': 'skin:hat',
                       'shop_price': 70,
                       'method_of_obtaining': 'shop:daily',
                       'rarity': '2',
                       'emoji': '🌈'
                       },
    'mcdonalds_cap': {'name': {'en': 'Mcdonalds_cap',
                         'ru': 'Кепка из мака'},
                'desc': {
                    'en': "The work of all programmers in the future",
                    'ru': 'Работа всех программистов в будущем'
                },
                'type': 'skin:hat',
                'shop_price': 70,
                'method_of_obtaining': 'shop:daily',
                'rarity': '2',
                'emoji': '🌈'
                },
    'z_cap_white': {'name': {'en': 'White Z cap',
                             'ru': 'Белая Z кепка'},
                    'desc': {
                        'en': 'White cap with letter Z',
                        'ru': 'Белая кепка с буквой Z'
                    },
                    'type': 'skin:hat',
                    'rarity': '2',
                    'emoji': '🧢'},
    'red_bandage': {'name': {'en': 'Red Bandage',
                             'ru': 'Красная повязка'},
                    'desc': {
                        'en': 'Stylish red headband',
                        'ru': 'Стильная красная повязка'
                    },
                    'type': 'skin:hat',
                    'shop_price': 60,
                    'method_of_obtaining': 'shop:daily',
                    'rarity': '2',
                    'emoji': '🧣'},
    'angel_hat': {'name': {'en': 'Angel',
                          'ru': 'Ангел'},
                 'desc': {
                     'en': "Don't be afraid...",
                     'ru': 'Не бойся...'
                 },
                 'type': 'skin:hat',
                 'shop_price': 300,
                 'method_of_obtaining': 'shop:daily',
                 'rarity': '5',
                 'emoji': '👁️',
                  'not_draw': ['piercing_ear', 'glasses'],
                  },
    'vizard_hat': {'name': {'en': 'Vizard hat',
                           'ru': 'Шляпа волшебника'},
                  'desc': {
                      'en': "Pig can now cast spells",
                      'ru': 'Хряк теперь может колдовать'
                  },
                  'type': 'skin:hat',
                  'shop_price': 100,
                  'method_of_obtaining': 'shop:daily',
                  'rarity': '3',
                  'emoji': '🔮'
                  },
    'frog_hat': {'name': {'en': 'Frog hat',
                            'ru': 'Лягушачья панамка'},
                   'desc': {
                       'en': "Chill panama hat for chill boar",
                       'ru': 'Чиловая панамка для чилового хряка'
                   },
                   'type': 'skin:hat',
                   'shop_price': 90,
                   'method_of_obtaining': 'shop:daily',
                   'rarity': '3',
                   'emoji': '🐸'
                   },
    'chef_hat': {'name': {'en': 'Chef hat',
                          'ru': 'Шляпа шефа'},
                 'desc': {
                     'en': 'Only real chefs can wear this',
                     'ru': 'Только настоящие повара могут носить такое'
                 },
                 'type': 'skin:hat',
                 'shop_price': 80,
                 'method_of_obtaining': 'shop:daily',
                 'rarity': '3',
                 'emoji': '🎩'},
    'military_cap': {'name': {'en': 'Military cap',
                              'ru': 'Военная шляпа'},
                     'desc': {
                         'en': 'With this hat you can immediately go to Bakhmut',
                         'ru': 'С этой шапкой можно сразу в Бахмут'
                     },
                     'type': 'skin:hat',
                     'shop_price': 80,
                     'method_of_obtaining': 'shop:daily',
                     'rarity': '3',
                     'emoji': '🪖'},
    'blue_wreath': {'name': {'en': 'Blue wreath',
                             'ru': 'Голубой венок'},
                    'desc': {
                        'en': 'Blue flower wreath',
                        'ru': 'Венок из голубых цветов'
                    },
                    'type': 'skin:hat',
                    'shop_price': 170,
                    'method_of_obtaining': 'shop:daily',
                    'rarity': '4',
                    'emoji': '🌺'},
    'pink_wreath': {'name': {'en': 'Pink wreath',
                             'ru': 'Розовый венок'},
                    'desc': {
                        'en': 'Pink flower wreath',
                        'ru': 'Венок из розовых цветов'
                    },
                    'type': 'skin:hat',
                    'shop_price': 140,
                    'method_of_obtaining': 'shop:daily',
                    'rarity': '3',
                    'emoji': '🌺'},
    'fire_diadem': {'name': {'en': 'Fire diadem',
                             'ru': 'Огненная корона'},
                    'desc': {
                        'en': 'With such a crown it will always be warm',
                        'ru': 'С такой короной будет всегда тепло'
                    },
                    'type': 'skin:hat',
                    'shop_price': 180,
                    'method_of_obtaining': 'shop:daily',
                    'rarity': '4',
                    'emoji': '🔥'},
    'headphones': {'name': {'en': 'Headphones',
                            'ru': 'Наушники'},
                   'desc': {
                       'en': "You can't hear anything in them, but they look cool",
                       'ru': 'Нарисуйте кто нибудь нормальные наушники и киньте создателю'
                   },
                   'type': 'skin:hat',
                   'shop_price': 100,
                   'method_of_obtaining': 'shop:daily',
                   'rarity': '3',
                   'emoji': '🎧'},
    'old_man_hat': {'name': {'en': 'Old man hat',
                             'ru': 'Дедовская шляпа'},
                    'desc': {
                        'en': 'Very cool hat if you are an old guy',
                        'ru': 'Очень крутая шляпа, если ты дед'
                    },
                    'type': 'skin:hat',
                    'shop_price': 80,
                    'method_of_obtaining': 'shop:daily',
                    'rarity': '3',
                    'emoji': '🎩'},
    'white_cap': {'name': {'en': 'White cap',
                           'ru': 'Белая кепка'},
                  'desc': {
                      'en': 'White cap, nothing else',
                      'ru': 'Белая кепка, ничего больше'
                  },
                  'type': 'skin:hat',
                  'shop_price': 70,
                  'method_of_obtaining': 'shop:daily',
                  'rarity': '3',
                  'emoji': '🧢'},
    'straw_hat': {'name': {'en': 'Straw hat',
                           'ru': 'Соломенная шляпа'},
                  'desc': {
                      'en': 'Looks very stylish',
                      'ru': 'Выглядит очень стильно'
                  },
                  'type': 'skin:hat',
                  'shop_price': 100,
                  'method_of_obtaining': 'shop:daily',
                  'rarity': '3',
                  'emoji': '👒'},
    'poop_hat': {'name': {'en': 'Poop hat',
                          'ru': 'Навозная шляпа'},
                 'desc': {
                     'en': 'It smells so good',
                     'ru': 'Воняет пизд..ц'
                 },
                 'type': 'skin:hat',
                 'shop_price': 100,
                 'method_of_obtaining': 'shop:daily',
                 'rarity': '3',
                 'emoji': '💩'},
    'pig_king_crown': {'name': {'en': 'Pig king crown',
                                'ru': 'Корона короля свиней'},
                       'desc': {
                           'en': 'Only kings can wear this',
                           'ru': 'Только короли могут носить такое'
                       },
                       'type': 'skin:hat',
                       'shop_price': 200,
                       'method_of_obtaining': 'shop:daily',
                       'rarity': '4',
                       'emoji': '👑'},
    'demon_horns': {'name': {'en': 'Demon horns',
                             'ru': 'Рога демона'},
                    'desc': {
                        'en': 'Bad pig, the most terrible that exists',
                        'ru': 'Плохой хряк, самый ужасный который только существует'
                    },
                    'type': 'skin:hat',
                    'shop_price': 180,
                    'method_of_obtaining': 'shop:daily',
                    'rarity': '4',
                    'emoji': '👿'},
    'purple_demon_horns': {'name': {'en': 'Purple demon horns',
                             'ru': 'Фиолетовые рога демона'},
                    'desc': {
                        'en': 'Bad pig, the most terrible that exists',
                        'ru': 'Плохой хряк, самый ужасный который только существует'
                    },
                    'type': 'skin:hat',
                    'shop_price': 180,
                    'method_of_obtaining': 'shop:daily',
                    'rarity': '4',
                    'emoji': '👿'},
    'nimbus': {'name': {'en': 'Nimbus',
                        'ru': 'Нимб'},
               'desc': {
                   'en': 'Pigs always go to heaven',
                   'ru': 'Хряки всегда попадают в рай'
               },
               'type': 'skin:hat',
               'shop_price': 150,
               'method_of_obtaining': 'shop:daily',
               'rarity': '4',
               'emoji': '😇'},
    'clown_hat': {'name': {'en': 'Clown hair',
                           'ru': 'Клоунский парик'},
                  'desc': {
                      'en': 'Especially for those who support war',
                      'ru': 'Специально для тех, кто поддерживает коммунизм'
                  },
                  'type': 'skin:hat',
                  'shop_price': 110,
                  'method_of_obtaining': 'shop:daily',
                  'rarity': '3',
                  'emoji': '🤡'},
    'robbin_good_hat': {'name': {'en': 'Robin Hood hat',
                                 'ru': 'Шляпа Робин Гуда'},
                        'desc': {
                            'en': 'Steal from the poor and give to the rich',
                            'ru': 'Воруйте у бедных и отдавайте богатым'
                        },
                        'type': 'skin:hat',
                        'shop_price': 100,
                        'method_of_obtaining': 'shop:daily',
                        'rarity': '3',
                        'emoji': '💸'},
    'american_hat': {'name': {'en': 'American hat',
                              'ru': 'Американская шляпа'},
                     'desc': {
                         'en': 'A hat in which you can feel freedom',
                         'ru': 'Шляпа, в которой можно почувствовать свободу'
                     },
                     'type': 'skin:hat',
                     'shop_price': 120,
                     'method_of_obtaining': 'shop:daily',
                     'rarity': '3',
                     'emoji': '🌎'},
    'pirate_hat': {'name': {'en': 'Pirate hat',
                            'ru': 'Пиратская шляпа'},
                   'desc': {
                       'en': 'Rob, kill and bathe in gold. And then die at 30',
                       'ru': 'Грабь, убивай и купайся в золоте. А потом умри в 30'
                   },
                   'type': 'skin:hat',
                   'shop_price': 140,
                   'method_of_obtaining': 'shop:daily',
                   'rarity': '3',
                   'emoji': '🏴‍☠️'},
    'muzzle_of_a_tank': {'name': {'en': 'Muzzle of a tank',
                                  'ru': 'Дуло от танка'},
                         'desc': {
                             'en': 'Become a war pig with this gun',
                             'ru': 'Станьте военным свином с помощью этой пушки'
                         },
                         'type': 'skin:hat',
                         'shop_price': 200,
                         'method_of_obtaining': 'shop:daily',
                         'rarity': '4',
                         'emoji': '🔫'},

    # glasses
    'pixel_glasses': {'name': {'en': 'Pixel Glasses',
                               'ru': 'Пикскельные очки'},
                      'desc': {
                          'en': 'Cool pixel glasses',
                          'ru': 'Крутые пиксельные очки'
                      },
                      'type': 'skin:glasses',
                      'shop_price': 240,
                      'method_of_obtaining': 'shop:daily',
                      'rarity': '4',
                      'emoji': '🕶️',
                      'not_draw': ['eyes', 'pupils']},
    'sunglasses': {'name': {'en': 'Sunglasses',
                            'ru': 'Солнцезащитные очки'},
                   'desc': {
                       'en': 'With these glasses you can not be afraid of the sun',
                       'ru': 'С этими очками можно не боятся солнца'
                   },
                   'type': 'skin:glasses',
                   'shop_price': 90,
                   'method_of_obtaining': 'shop:daily',
                   'rarity': '3',
                   'emoji': '🕶️',
                   'not_draw': ['eyes', 'pupils']},
    'star_glasses': {'name': {'en': 'Star glasses',
                              'ru': 'Звёздные очки'},
                     'desc': {
                         'en': 'Shine like a star with these glasses',
                         'ru': 'Сияй как звезда с этими очками'
                     },
                     'type': 'skin:glasses',
                     'shop_price': 130,
                     'method_of_obtaining': 'shop:daily',
                     'rarity': '3',
                     'emoji': '🕶️'},
    'fire_glasses': {'name': {'en': 'Fire glasses',
                              'ru': 'Огненные очки'},
                     'desc': {
                         'en': 'Cool glasses in the form of fire',
                         'ru': 'Крутые очки в форме огня'
                     },
                     'type': 'skin:glasses',
                     'shop_price': 130,
                     'method_of_obtaining': 'shop:daily',
                     'rarity': '3',
                     'emoji': '🕶️'},
    'rounded_glasses': {'name': {'en': 'Rounded glasses',
                                 'ru': 'Закруглённые очки'},
                        'desc': {
                            'en': 'People say they improve eyesight',
                            'ru': 'Говорят что они улучшают зрение'
                        },
                        'type': 'skin:glasses',
                        'shop_price': 50,
                        'method_of_obtaining': 'shop:daily',
                        'rarity': '3',
                        'emoji': '👓'},
    'round_glasses': {'name': {'en': 'Round glasses',
                               'ru': 'Круглые очки'},
                      'desc': {
                          'en': 'You will look like Harry Potter',
                          'ru': 'Вы будете выглядеть как Гарри Потер'
                      },
                      'type': 'skin:glasses',
                      'shop_price': 60,
                      'method_of_obtaining': 'shop:daily',
                      'rarity': '3',
                      'emoji': '👓'},
    'nahodkins_glasses': {'name': {'en': 'Green glasses',
                               'ru': 'Очки Находкинса'},
                      'desc': {
                          'en': 'Well, am I that bad?',
                          'ru': 'Ну разве я такой уж плохой?'
                      },
                      'type': 'skin:glasses',
                      'shop_price': 120,
                      'method_of_obtaining': 'shop:daily',
                      'rarity': '3',
                      'emoji': '👓',
                    'not_draw': ['eyes']},
    'eye_patch': {'name': {'en': 'Eye patch',
                           'ru': 'Повязка на глаз'},
                  'desc': {
                      'en': 'Cool eye patch, just like the pirates',
                      'ru': 'Крутая повязка на глаз, прям как у пиратов'
                  },
                  'type': 'skin:glasses',
                  'shop_price': 80,
                  'method_of_obtaining': 'shop:daily',
                  'rarity': '3',
                  'emoji': '🏴‍☠️'},
    'monocle': {'name': {'en': 'Monocle',
                         'ru': 'Монокль'},
                'desc': {
                    'en': 'What a cultured and educated pig',
                    'ru': 'Какой культурный и воспитанный хряк'
                },
                'type': 'skin:glasses',
                'shop_price': 100,
                'method_of_obtaining': 'shop:daily',
                'rarity': '3',
                'emoji': '🧐'},

    # ties
    'bow_tie': {'name': {'en': 'Bow tie',
                         'ru': 'Галстук-бабочка'},
                'desc': {
                    'en': 'With a bow tie you will be like a real gentleman',
                    'ru': 'С бабочкой ты будешь как настоящий джентельмэн'
                },
                'type': 'skin:tie',
                'shop_price': 200,
                'method_of_obtaining': 'shop:daily',
                'rarity': '4',
                'emoji': '👔'},
    'black_tie': {'name': {'en': 'Tie',
                         'ru': 'Галстук'},
                'desc': {
                    'en': 'Mega business red tie',
                    'ru': 'Мега деловой красный галстук'
                },
                'type': 'skin:tie',
                'shop_price': 200,
                'method_of_obtaining': 'shop:daily',
                'rarity': '4',
                'emoji': '👔'},
    'red_tie': {'name': {'en': 'Red tie',
                         'ru': 'Красный галстук'},
                'desc': {
                    'en': 'Mega business red tie',
                    'ru': 'Мега деловой красный галстук'
                },
                'type': 'skin:tie',
                'shop_price': 200,
                'method_of_obtaining': 'shop:daily',
                'rarity': '4',
                'emoji': '👔'},

    # noses
    'clown_nose': {'name': {'en': 'Clown nose',
                            'ru': 'Нос клоуна'},
                   'desc': {
                       'en': 'Great for you if you feel like a clown',
                       'ru': 'Отлично подойдёт вам, если вы чувствуете себя клоуном'
                   },
                   'type': 'skin:_nose',
                   'shop_price': 120,
                   'method_of_obtaining': 'shop:daily',
                   'not_draw': ['piercing_nose', 'nose'],
                   'rarity': '3',
                   'emoji': '🔴'},

    # faces
    'amogus_glasses': {'name': {'en': 'Amogus face',
                                'ru': 'Лицо амогуса'},
                       'desc': {
                           'en': 'Feel like a real amogus',
                           'ru': 'Почувствуй себя настоящим амогусом'
                       },
                       'type': 'skin:face',
                       'shop_price': 3000,
                       # 'method_of_obtaining': 'shop:daily',
                       'rarity': '6',
                       'emoji': '📮',
                       'not_draw': ['eyes', 'pupils', 'nose', '_nose', 'makeup', 'glasses', 'piercing_nose']},
    'hyak_face': {'name': {'en': 'Hyak face',
                                'ru': 'Лицо Хяка'},
                       'desc': {
                           'en': 'Oh, this is the legendary Hyak',
                           'ru': 'Да это же легендарный Хяк'
                       },
                       'type': 'skin:face',
                       'shop_price': 2000,
                       # 'method_of_obtaining': 'shop:daily',
                       'rarity': '6',
                       'emoji': '😐',
                       'not_draw': ['eyes', 'pupils', 'nose', '_nose', 'makeup', 'glasses', 'piercing_nose']},

    # legs
    'tank_tracks': {'name': {'en': 'Tank tracks',
                             'ru': 'Гусеницы от танка'},
                    'desc': {
                        'en': 'The very thing for traveling to the Ukr ... Well, okay, the joke is not funny',
                        'ru': 'Самое то для путешествий в Ук... А ладно, шутка не смешная'
                    },
                    'type': 'skin:legs',
                    'shop_price': 1100,
                    # 'method_of_obtaining': 'shop:daily',
                    'rarity': '6',
                    'emoji': '🐛'},

    # bodies
    'gold_body': {'name': {'en': 'Gold paint',
                           'ru': 'Золотая краска'},
                  'desc': {
                      'en': 'Gold paint for pig',
                      'ru': 'Золотая краска для хряка'
                  },
                  'type': 'skin:body',
                  # 'shop_price': 100,
                  'method_of_obtaining': 'premium',
                  'rarity': '6',
                  'emoji': '🎨'},
    'dark_body': {'name': {'en': 'Chocolate paint',
                           'ru': 'Шоколадная краска'},
                  'desc': {
                      'en': 'Chocolate paint for pig',
                      'ru': 'Шоколадная краска для хряка'
                  },
                  'type': 'skin:body',
                  'shop_price': 500,
                  'method_of_obtaining': 'shop:daily',
                  'rarity': '5',
                  'emoji': '🎨'},
    'lgbt_body': {'name': {'en': 'LGBT paint',
                           'ru': 'ЛГБТ краска'},
                  'desc': {
                      'en': 'LGBT paint for pig',
                      'ru': 'ЛГБТ краска для хряка'
                  },
                  'type': 'skin:body',
                  # 'shop_price': 100,
                  # 'method_of_obtaining': 'premium',
                  'rarity': '5',
                  'emoji': '🎨'},
    'green_body': {'name': {'en': 'Green paint',
                            'ru': 'Зелёная краска'},
                   'desc': {
                       'en': 'Green paint for pig',
                       'ru': 'Зелёная краска для хряка'
                   },
                   'type': 'skin:body',
                   'shop_price': 500,
                   'method_of_obtaining': 'shop:daily',
                   'rarity': '5',
                   'emoji': '🎨'},
    'spider_body': {'name': {'en': 'Spider paint',
                             'ru': 'Паучья краска'},
                    'desc': {
                        'en': 'A pig spider lives in one of the universes',
                        'ru': 'В одной из вселенных проживает хряк-паук'
                    },
                    'type': 'skin:body',
                    'shop_price': 700,
                    'method_of_obtaining': 'shop:daily',
                    'rarity': '5',
                    'emoji': '🎨'},
    'shark_body': {'name': {'en': 'Shark paint',
                             'ru': 'Акулья краска'},
                    'desc': {
                        'en': 'Baby shark tu-tu-tu-tu, baby shark tu-tu-tu-tu',
                        'ru': 'Акулёнок ту-ту-ту-ту, акулёнок ту-ту-ту-ту'
                    },
                    'type': 'skin:body',
                    'shop_price': 900,
                    'method_of_obtaining': 'shop:daily',
                    'rarity': '5',
                    'emoji': '🎨'},
    'cat_body': {'name': {'en': 'Mew-paint',
                            'ru': 'Мяу-краска'},
                   'desc': {
                       'en': 'It seems the pig has ceased to be a pig',
                       'ru': 'Кажется Хряк перестал быть Хряком'
                   },
                   'type': 'skin:body',
                   'shop_price': 900,
                   'method_of_obtaining': 'shop:daily',
                   'rarity': '5',
                   'emoji': '🎨'},
    'cow_body': {'name': {'en': 'Cow paint',
                            'ru': 'Коровья краска'},
                   'desc': {
                       'en': 'Muuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu',
                       'ru': 'Мууууууууууууууууууууууууууууууууууууууууууу'
                   },
                   'type': 'skin:body',
                   'shop_price': 850,
                   'method_of_obtaining': 'shop:daily',
                   'rarity': '5',
                   'emoji': '🎨'},
    'white_body': {'name': {'en': 'White paint',
                             'ru': 'Белая краска'},
                    'desc': {
                        'en': 'Be the whitest and purest Boar',
                        'ru': 'Будь самым белым и чистым Хряком'
                    },
                    'type': 'skin:body',
                    'shop_price': 500,
                    'method_of_obtaining': 'shop:daily',
                    'rarity': '5',
                    'emoji': '🎨'},
    'robot_body': {'name': {'en': 'Robot paint',
                            'ru': 'Краска робота'},
                   'desc': {
                       'en': 'Pig to eat, the pig is happy. beep boop',
                       'ru': 'Хряк кушать, хряк доволен. Бип-буп'
                   },
                   'type': 'skin:body',
                   'shop_price': 800,
                   'method_of_obtaining': 'shop:daily',
                   'rarity': '5',
                   'emoji': '🎨'},
    'bea_body': {'name': {'en': 'Bea paint',
                            'ru': 'Пчелиная краска'},
                   'desc': {
                       'en': 'Bzz-bzzzzzz. Bz-bzz',
                       'ru': 'Бзз-бзззззз. Бз-бзз'
                   },
                   'type': 'skin:body',
                   'shop_price': 800,
                   'method_of_obtaining': 'shop:daily',
                   'rarity': '5',
                   'emoji': '🎨'},
    'cheese_body': {'name': {'en': 'Cheese paint',
                          'ru': 'Сырная краска'},
                 'desc': {
                     'en': 'Very tasty pig with the taste of cheese and sponge',
                     'ru': 'Очень вкусный хряк со вкусом сыра и губки'
                 },
                 'type': 'skin:body',
                 'shop_price': 700,
                 'method_of_obtaining': 'shop:daily',
                 'rarity': '5',
                 'emoji': '🎨'},
    'camouflage_body': {'name': {'en': 'Camouflage paint',
                                 'ru': 'Камуфляжная краска'},
                        'desc': {
                            'en': 'With this paint you will become almost invisible',
                            'ru': 'С этой краской вы станете почти невидимым'
                        },
                        'type': 'skin:body',
                        'shop_price': 600,
                        'method_of_obtaining': 'shop:daily',
                        'rarity': '5',
                        'emoji': '🎨'},

    # suits
    'space_suit': {'name': {'en': 'Space suit',
                            'ru': 'Скафандр'},
                   'desc': {
                       'en': 'Almost ready to fly into space',
                       'ru': 'К полёту в космос почти готов'
                   },
                   'type': 'skin:suit',
                   'shop_price': 800,
                   'method_of_obtaining': 'shop:daily',
                   'rarity': '5',
                   'not_draw': ['piercing_ear', 'glasses', 'paint', 'amogus_glasses'],
                   'emoji': '🚀'},
    'summer_dress': {'name': {'en': 'Summer dress',
                            'ru': 'Летнее платье'},
                   'desc': {
                       'en': 'Dress for Pig? Why not',
                       'ru': 'Платье на Хряка? Почему бы и нет'
                   },
                   'type': 'skin:suit',
                   'shop_price': 700,
                   'method_of_obtaining': 'shop:daily',
                   'rarity': '5',
                   'not_draw': ['tie'],
                   'emoji': '🚀'},

    # makeups
    'cry_makeup': {'name': {'en': 'Dripping mascara',
                            'ru': 'Потёкшая тушь'},
                   'desc': {
                       'en': 'Pig cry-cry. Pig be sad',
                       'ru': 'Хряк плак-плак. Хряк грустить'
                   },
                   'type': 'skin:makeup',
                   'shop_price': 240,
                   'method_of_obtaining': 'shop:daily',
                   'rarity': '4',
                   'emoji': '💄'},
    'clown_makeup': {'name': {'en': 'Clown makeup',
                            'ru': 'Клоунский макияж'},
                   'desc': {
                       'en': 'For real clowns',
                       'ru': 'Для самых настоящих клоунов'
                   },
                   'type': 'skin:makeup',
                   'shop_price': 120,
                   'method_of_obtaining': 'shop:daily',
                   'rarity': '3',
                   'emoji': '💄'},
    'blush': {'name': {'en': 'Blush',
                              'ru': 'Румянец'},
                     'desc': {
                         'en': "It's so pretty",
                         'ru': 'Это так мило'
                     },
                     'type': 'skin:makeup',
                     'shop_price': 150,
                     'method_of_obtaining': 'shop:daily',
                     'rarity': '3',
                     'emoji': '💄'},
    'eye_fingal': {'name': {'en': 'Fingal',
                            'ru': 'Фингал'},
                   'desc': {
                       'en': "Just put some ice on and it'll go away",
                       'ru': 'Просто приложи лед и всё пройдёт'
                   },
                   'type': 'skin:makeup',
                   'shop_price': 130,
                   'method_of_obtaining': 'shop:daily',
                   'rarity': '3',
                   'emoji': '💄'},
    'eye_scar': {'name': {'en': 'Eye scar',
                            'ru': 'Шрам на глазе'},
                   'desc': {
                       'en': 'Scar on the eye, what else to say',
                       'ru': 'Шрам на глазе, что еще сказать'
                   },
                   'type': 'skin:makeup',
                   'shop_price': 210,
                   'method_of_obtaining': 'shop:daily',
                   'rarity': '4',
                   'emoji': '💄'},
    'star_makeup': {'name': {'en': 'Star makeup',
                          'ru': 'Звездный макияж'},
                 'desc': {
                     'en': 'A star on the eye',
                     'ru': 'Звезда на глазе'
                 },
                 'type': 'skin:makeup',
                 'shop_price': 200,
                 'method_of_obtaining': 'shop:daily',
                 'rarity': '4',
                 'emoji': '💄'},
    'black_makeup': {'name': {'en': 'Black makeup',
                             'ru': 'Чёрный макияж'},
                    'desc': {
                        'en': 'For those who find life too bright',
                        'ru': 'Для тех, кому жизнь кажется слишком светлой'
                    },
                    'type': 'skin:makeup',
                    'shop_price': 190,
                    'method_of_obtaining': 'shop:daily',
                    'rarity': '4',
                    'emoji': '💄'},
    'unibrow': {'name': {'en': 'Unibrow',
                             'ru': 'Монобровь'},
                    'desc': {
                        'en': 'One hamburger, bro',
                        'ru': 'Одну сырную, брат'
                    },
                    'type': 'skin:makeup',
                    'shop_price': 200,
                    'method_of_obtaining': 'shop:daily',
                    'rarity': '4',
                    'emoji': '💄'},

    # piercings
    'gold_ear_piercing': {'name': {'en': 'Gold piercing (Ear)',
                                   'ru': 'Золотой пирсинг (Ухо)'},
                          'desc': piercing_description,
                          'type': 'skin:piercing_ear',
                          'shop_price': 140,
                          'method_of_obtaining': 'shop:daily',
                          'rarity': '3',
                          'emoji': '💍'},
    'silver_ear_piercing': {'name': {'en': 'Silver piercing (Ear)',
                                     'ru': 'Серебряный пирсинг (Ухо)'},
                            'desc': piercing_description,
                            'type': 'skin:piercing_ear',
                            'shop_price': 140,
                            'method_of_obtaining': 'shop:daily',
                            'rarity': '3',
                            'emoji': '💍'},
    'skull_piercing': {'name': {'en': 'Skull piercing',
                                     'ru': 'Пирсинг - череп'},
                            'desc': piercing_description,
                            'type': 'skin:piercing_ear',
                            'shop_price': 140,
                            'method_of_obtaining': 'shop:daily',
                            'rarity': '3',
                            'emoji': '💍'},

    'gold_nose_piercing': {'name': {'en': 'Gold piercing (Nose)',
                                    'ru': 'Золотой пирсинг (Нос)'},
                           'desc': piercing_description,
                           'type': 'skin:piercing_nose',
                           'shop_price': 140,
                           'method_of_obtaining': 'shop:daily',
                           'rarity': '3',
                           'emoji': '💍'},

    'silver_nose_piercing': {'name': {'en': 'Silver piercing (Nose)',
                                      'ru': 'Серебряный пирсинг (Нос)'},
                             'desc': piercing_description,
                             'type': 'skin:piercing_nose',
                             'shop_price': 140,
                             'method_of_obtaining': 'shop:daily',
                             'rarity': '3',
                             'emoji': '💍'},

    # eyes
    'black_eyes': {'name': {'en': 'Big black lenses',
                            'ru': 'Большие черные линзы'},
                   'desc': eyes_description,
                   'type': 'skin:eyes',
                   'shop_price': 250,
                   'method_of_obtaining': 'shop:daily',
                   'rarity': '4',
                   'emoji': '👁️'},
    'crazy_eyes': {'name': {'en': 'Big crazy lenses',
                            'ru': 'Большие безумные линзы'},
                   'desc': eyes_description,
                   'type': 'skin:eyes',
                   'shop_price': 250,
                   'method_of_obtaining': 'shop:daily',
                   'rarity': '4',
                   'emoji': '👁️'},

    # pupils
    'black_pupils': {'name': {'en': 'Black lenses',
                             'ru': 'Чёрные линзы'},
                    'desc': lenses_description,
                    'type': 'skin:pupils',
                    'shop_price': default_lenses_price,
                    'method_of_obtaining': 'shop:daily',
                    'rarity': '2',
                    'emoji': '👁️'},
    'blue_pupils': {'name': {'en': 'Blue lenses',
                             'ru': 'Голубые линзы'},
                    'desc': lenses_description,
                    'type': 'skin:pupils',
                    'shop_price': default_lenses_price,
                    'method_of_obtaining': 'shop:daily',
                    'rarity': '2',
                    'emoji': '👁️'},
    'green_pupils': {'name': {'en': 'Green lenses',
                              'ru': 'Зеленые линзы'},
                     'desc': lenses_description,
                     'type': 'skin:pupils',
                     'shop_price': default_lenses_price,
                     'method_of_obtaining': 'shop:daily',
                     'rarity': '2',
                     'emoji': '👁️'},
    'orange_pupils': {'name': {'en': 'Orange lenses',
                               'ru': 'Оранжевые линзы'},
                      'desc': lenses_description,
                      'type': 'skin:pupils',
                      'shop_price': default_lenses_price,
                      'method_of_obtaining': 'shop:daily',
                      'rarity': '2',
                      'emoji': '👁️'},
    'pink_pupils': {'name': {'en': 'Pink lenses',
                             'ru': 'Розовые линзы'},
                    'desc': lenses_description,
                    'type': 'skin:pupils',
                    'shop_price': default_lenses_price,
                    'method_of_obtaining': 'shop:daily',
                    'rarity': '2',
                    'emoji': '👁️'},
    'purple_pupils': {'name': {'en': 'Purple lenses',
                               'ru': 'Фиолетовые линзы'},
                      'desc': lenses_description,
                      'type': 'skin:pupils',
                      'shop_price': default_lenses_price,
                      'method_of_obtaining': 'shop:daily',
                      'rarity': '2',
                      'emoji': '👁️'},
    'red_pupils': {'name': {'en': 'Red lenses',
                            'ru': 'Красные линзы'},
                   'desc': lenses_description,
                   'type': 'skin:pupils',
                   'shop_price': 100,
                   'method_of_obtaining': 'shop:daily',
                   'rarity': '2',
                   'emoji': '👁️'},
    'white_pupils': {'name': {'en': 'White lenses',
                              'ru': 'Белые линзы'},
                     'desc': lenses_description,
                     'type': 'skin:pupils',
                     'shop_price': 150,
                     'method_of_obtaining': 'shop:daily',
                     'rarity': '4',
                     'emoji': '👁️'},
    'yellow_pupils': {'name': {'en': 'Yellow lenses',
                               'ru': 'Желтые линзы'},
                      'desc': lenses_description,
                      'type': 'skin:pupils',
                      'shop_price': default_lenses_price,
                      'method_of_obtaining': 'shop:daily',
                      'rarity': '2',
                      'emoji': '👁️'},
    'magic_pupils': {'name': {'en': 'Magic lenses',
                               'ru': 'Магические линзы'},
                      'desc': lenses_description,
                      'type': 'skin:pupils',
                      'shop_price': 120,
                      'method_of_obtaining': 'shop:daily',
                      'rarity': '3',
                      'emoji': '👁️'},
    'rick_pupils': {'name': {'en': "Rick's lenses",
                              'ru': 'Линзы Рика'},
                     'desc': lenses_description,
                     'type': 'skin:pupils',
                     'shop_price': 120,
                     'method_of_obtaining': 'shop:daily',
                     'rarity': '3',
                     'emoji': '👁️'},
    'gold_pupils': {'name': {'en': 'Gold lenses',
                             'ru': 'Золотые линзы'},
                    'desc': lenses_description,
                    'type': 'skin:pupils',
                    # 'shop_price': default_lenses_price,
                    # 'method_of_obtaining': 'shop:daily',
                    'rarity': '6',
                    'emoji': '👁️'},

    # tattoos
    'applejack_mark': {'name': {'en': 'Applejack cutie mark',
                                'ru': 'Эплджек - катушек'},
                       'desc': tattoo_description,
                       'type': 'skin:tattoo',
                       'shop_price': default_tattoo_price,
                       'method_of_obtaining': 'shop:daily',
                       'rarity': '2',
                       'emoji': '🐉'},
    'fluttershy_mark': {'name': {'en': 'Fluttershy cutie mark',
                                 'ru': 'Флаттершай - катушек'},
                        'desc': tattoo_description,
                        'type': 'skin:tattoo',
                        'shop_price': default_tattoo_price,
                        'method_of_obtaining': 'shop:daily',
                        'rarity': '2',
                        'emoji': '🐉'},
    'pinkie_pie_mark': {'name': {'en': 'Pinkie Pie cutie mark',
                                 'ru': 'Пинки Пай - катушек'},
                        'desc': tattoo_description,
                        'type': 'skin:tattoo',
                        'shop_price': default_tattoo_price,
                        'method_of_obtaining': 'shop:daily',
                        'rarity': '2',
                        'emoji': '🐉'},
    'rainbow_dash_mark': {'name': {'en': 'Rainbow Dash cutie mark',
                                   'ru': 'Рэйнбоу Дэш - катушек'},
                          'desc': tattoo_description,
                          'type': 'skin:tattoo',
                          'shop_price': default_tattoo_price,
                          'method_of_obtaining': 'shop:daily',
                          'rarity': '2',
                          'emoji': '🐉'},
    'rarity_mark': {'name': {'en': 'Rarity cutie mark',
                             'ru': 'Рарити - катушек'},
                    'desc': tattoo_description,
                    'type': 'skin:tattoo',
                    'shop_price': default_tattoo_price,
                    'method_of_obtaining': 'shop:daily',
                    'rarity': '2',
                    'emoji': '🐉'},
    'twilight_parkle_mark': {'name': {'en': 'Twilight Parkle cutie mark',
                                      'ru': 'Искорка - катушек'},
                             'desc': tattoo_description,
                             'type': 'skin:tattoo',
                             'shop_price': default_tattoo_price,
                             'method_of_obtaining': 'shop:daily',
                             'rarity': '2',
                             'emoji': '🐉'},
    'target_mark': {'name': {'en': 'Target tattoo',
                             'ru': 'Тату - мишень'},
                    'desc': tattoo_description,
                    'type': 'skin:tattoo',
                    'shop_price': default_tattoo_price,
                    'method_of_obtaining': 'shop:daily',
                    'rarity': '2',
                    'emoji': '🐉'},
    'discord_mark': {'name': {'en': 'Discord tattoo',
                              'ru': 'Тату - дискорд'},
                     'desc': tattoo_description,
                     'type': 'skin:tattoo',
                     'shop_price': 60,
                     'method_of_obtaining': 'shop:daily',
                     'rarity': '2',
                     'emoji': '🐉'},
    'pentagram_tattoo': {'name': {'en': 'Pentagram tattoo',
                              'ru': 'Тату - пентаграмма'},
                     'desc': tattoo_description,
                     'type': 'skin:tattoo',
                     'shop_price': 40,
                     'method_of_obtaining': 'shop:daily',
                     'rarity': '2',
                     'emoji': '🐉'},
    'spider_mark': {'name': {'en': 'Spider tattoo',
                             'ru': 'Паук тату'},
                    'desc': tattoo_description,
                    'type': 'skin:tattoo',
                    'shop_price': 50,
                    'method_of_obtaining': 'shop:daily',
                    'rarity': '2',
                    'emoji': '🐉'},
    'ukraine_flag_mark': {'name': {'en': 'Ukrainian flag tattoo',
                                   'ru': 'Украинское тату'},
                          'desc': tattoo_description,
                          'type': 'skin:tattoo',
                          'shop_price': 40,
                          'method_of_obtaining': 'shop:daily',
                          'rarity': '2',
                          'emoji': '🐉'},
    'russian_flag_mark': {'name': {'en': 'Russian flag tattoo',
                                   'ru': 'Русское тату'},
                          'desc': tattoo_description,
                          'type': 'skin:tattoo',
                          'shop_price': 40,
                          'method_of_obtaining': 'shop:daily',
                          'rarity': '2',
                          'emoji': '🐉'},
    'morgenshtern_tattoo': {'name': {'en': 'Morgenshtern tatoo',
                                     'ru': 'Тату Моргенштерна'},
                            'desc': {
                                'en': tattoo_description['en'],
                                'ru': 'Татуха прям как у Моргенштерна!'
                            },
                            'type': 'skin:tattoo',
                            'shop_price': 100,
                            'method_of_obtaining': 'shop:daily',
                            'rarity': '4',
                            'emoji': '🐉'},
    'active_1_mark': {'name': {'en': 'Active 1 mark',
                                     'ru': 'Активность 1 - тату'},
                            'desc': tattoo_description,
                            'type': 'skin:tattoo',
                            'rarity': '4',
                            'emoji': '🐉'},
    'active_2_mark': {'name': {'en': 'Active 2 mark',
                                 'ru': 'Активность 2 - тату'},
                        'desc': tattoo_description,
                        'type': 'skin:makeup',
                        'rarity': '4',
                        'emoji': '🐉'},
    'active_3_mark': {'name': {'en': 'Active 3 mark',
                                 'ru': 'Активность 3 - тату'},
                        'desc': tattoo_description,
                        'type': 'skin:makeup',
                        'rarity': '4',
                        'emoji': '🐉'},
    'active_4_mark': {'name': {'en': 'Active 4 mark',
                                 'ru': 'Активность 4 - тату'},
                        'desc': tattoo_description,
                        'type': 'skin:makeup',
                        'rarity': '4',
                        'emoji': '🐉'},
    'active_5_mark': {'name': {'en': 'Active 5 mark',
                                 'ru': 'Активность 5 - тату'},
                        'desc': tattoo_description,
                        'type': 'skin:tattoo',
                        'rarity': '4',
                        'emoji': '🐉'},
    'active_6_mark': {'name': {'en': 'Active 6 mark',
                                 'ru': 'Активность 6 - тату'},
                        'desc': tattoo_description,
                        'type': 'skin:makeup',
                        'rarity': '4',
                        'emoji': '🐉'},
    'youtube_mark': {'name': {'en': 'Youtube mark',
                               'ru': 'Ютуб - тату'},
                      'desc': tattoo_description,
                      'type': 'skin:makeup',
                      'rarity': '4',
                      'emoji': '🐉'},
    'blue_heart_mark': {'name': {'en': 'Blue heart mark',
                              'ru': 'Голубое сердце - тату'},
                     'desc': tattoo_description,
                     'type': 'skin:makeup',
                     'rarity': '4',
                     'emoji': '🐉'},
    'face_anton_mark': {'name': {'en': 'Face of Anton',
                                 'ru': 'Ебало антона'},
                        'desc': tattoo_description,
                        'type': 'skin:tattoo',
                        'rarity': '6',
                        'emoji': '🐉'},
    'face_max_mark': {'name': {'en': 'Face of Maxim',
                               'ru': 'Ебало Максима'},
                      'desc': tattoo_description,
                      'type': 'skin:tattoo',
                      'rarity': '6',
                      'emoji': '🐉'},

    # eyes emotions
    # 'sad': {'name': {'en': 'Sad eyes',
    #                  'ru': 'Грустные глаза'},
    #         'desc': eye_emotion_description,
    #         'type': 'skin:eye_emotion',
    #         # 'shop_price': default_lenses_price,
    #         # 'method_of_obtaining': 'default',
    #         'rarity': '1',
    #         'emoji': '😔'},

}
